import json
import os

from dotenv import load_dotenv
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from langchain_openai import ChatOpenAI
from pydantic import BaseModel
from langchain_core.messages import SystemMessage,HumanMessage,AIMessage 

load_dotenv()

API_KEY = os.environ.get("API_KEY", "")
BASE_URL = os.environ.get("BASE_URL", "https://legion1.di.uoa.gr/v1")
MODEL = os.environ.get("MODEL", "llama3.1")

llm = ChatOpenAI(
    model=MODEL,
    base_url=BASE_URL,
    api_key=API_KEY or "missing",
    max_completion_tokens=2048,
)

app = FastAPI(title="Hyperion Agent")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

SYSTEM_PROMPT = """You are Hyperion, the AI assistant for the Hyper-AI IDE, you keep answers short and concise and you are helpful, clever and direct. """

MAX_HISTORY_MESSAGES = 10 

sessions : dict[str,list] = {}

def get_history(user_id:str) -> list:
    if user_id in sessions:
        return sessions[user_id]
    return []

def save_turn(user_id:str, user_message:str, ai_message:str):
    if user_id not in sessions:
        sessions[user_id] = []
    sessions[user_id].append(HumanMessage(content=user_message))
    sessions[user_id].append(AIMessage(content=ai_message))
    sessions[user_id] = sessions[user_id][-MAX_HISTORY_MESSAGES:]
 
class ChatRequest(BaseModel):
    user_id: str  # a UUID automatically generated by the IDE — use it to keep per-user session memory
    text: str  # the text the user typed in the chat


async def generate_reply(request: ChatRequest):
    messages = [SystemMessage(content=SYSTEM_PROMPT),
                *get_history(request.user_id),
                HumanMessage(content=request.text)]
    reply = ""
    try:
        async for chunk in llm.astream(messages):
            if chunk.text:
                reply += chunk.text
                yield f"data: {json.dumps({'response': chunk.text})}\n\n"
    except Exception as e:
        print(f"Error generating reply: {e}")
        yield f"data: {json.dumps({'response': f'Sorry, I could not reach the language model.'})}\n\n"
    else:
        save_turn(request.user_id, request.text, reply)
    yield "data: [DONE]\n\n"
    


@app.post("/chat")
async def chat(request: ChatRequest):
    return StreamingResponse(generate_reply(request), media_type="text/event-stream")


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
